//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidedService
    {
        public int Id { get; set; }
        public int Customer { get; set; }
        public System.DateTime Date { get; set; }
        public string Services { get; set; }
        public decimal Price { get; set; }
    
        public virtual Customer Customer1 { get; set; }
    }
}
